version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
