app_settings:
  app_name: "haircutmvp"
  app_port: 8000
  app_version: "1.0.0"
  app_host: "0.0.0.0"
  app_mount: "/api/v1"

db_settings:
  db_name: "postgres"
  db_user: "myuser"
  db_password: "mypassword"
  db_host: "localhost"
  db_port: 5432

redis_settings:
  redis_host: "localhost"
  redis_port: 6379

user_coefficients:
  common: 1
  vip: 0.5
  admin: 0.0
